monitor_paths = [
    "/Users/rahulsharma/.ssh",
    "/Users/rahulsharma/.config",
    "/Users/rahulsharma/Projects/filestat"
]

critical_paths = [
    "/Users/rahulsharma/.ssh"
]

snapshot_paths = [
    "/Users/rahulsharma/.ssh"
]

ignore = [
    "node_modules",
    ".git",
    "target",
    "src"
]